api.baseUrl=http://localhost:4111
api.version=/api/v1

admin.username=admin
admin.password=admin
admin.token=Basic YWRtaW46YWRtaW4=

ui.remote = http://selenoid/wd/hub
ui.baseUrl = http://nginx
ui.browser = chrome
ui.browserSize = 1920x1080
ui.timeout = 10000

# Database configuration
db.url=jdbc:postgresql://docker_compose-postgres-1/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

selenoid.url=http://selenoid
selenoid.ui.url=http://selenoid-ui