api.baseUrl=http://localhost:4111
api.version=/api/v1

admin.username=admin
admin.password=admin
admin.token=Basic YWRtaW46YWRtaW4=

ui.remote = http://localhost:4444/wd/hub
ui.baseUrl = http://frontend:80
ui.browser = chrome
ui.browserSize = 1920x1080
ui.timeout = 10000

# Database configuration
db.url=jdbc:postgresql://localhost:5432/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

selenoid.url=http://localhost:4444
selenoid.ui.url=http://selenoid-ui