{
 "title": "Total Metrics Dashboard",
 "tags": [ "tests" ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Созданные пользователи",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "user_created_total" }
   ]
  },
  {
   "title": "Начатые переводы",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "transfer_started_total" }
   ]
  },
  {
   "title": "Успешные переводы",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "transfer_success_total" }
   ]
  },
  {
   "title": "Неудачные переводы",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "transfer_failed_total" }
   ]
  },
  {
   "title": "Удаление пользователей админом",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "admin_user_deleted_total" }
   ]
  },
  {
   "title": "Открытые счета",
   "type": "graph",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "account_created_total" }
   ]
  },
  {
   "title": "Просмотр профиля клиента",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    { "expr": "customer_profile_fetched_total" }
   ]
  },
  {
   "title": "Входы пользователей",
   "type": "graph",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    { "expr": "user_login_total" }
   ]
  }
 ]
}