---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bGFMZV81OGM3TmY6NU9xUC1uWjhQQkhIQEpPYitvYz9VN20/Zj9rMCRPVWR2MjNPR2IhJGpLZUF6dmE2ZFdjLVFrVGh1LWF3QUtGWjczSHJIZHJoRnJkMGpYZ3FCYytRVnZIIUU0OExyakgrUENiMHlQbS1ldFVldkR3MWhkRnBtMnNiWmJWNj84aXJZNjJONiVSP3RJMEF6SnRYajBWMStqTFREZ0VmSHdFV1RPUENkNDBwdj91LXJ0ZDV0K1ZAc0w1eUcySEZqRmxJTURNV0FlYnlmVWJCRUlHY3JLWnhKV0NCVEtTbmR5UEZvRG1Z"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
