---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/deposit:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic aUNobnNPYnpiVzpNJWROQTlySE11cUMhTUo2TUlISDArSnZFNjYhV1Y4MWV4YWdKUWN2bHZpTFFKKytPeWZQRWtqSm1Bb2RKQ2R4cGxKUkprdnFoWWFIUld6TEh6UVkzZ2FGTjY1JmVMQmEmaDJsdHlCZSs4WjlKR3pJSEwkZFclb0htUjJ3NGNPcUNqT3J1WHlCaVlBMEt0ZUZTWStiODZUbGN2TU9VeFh3cWwkV3dAIStqZ20lYWR1QE9jSnhmVHYzbXNAeEpvdUxLcnZ0YkNBb21mVHJVMlVod1pSb3lPSGFxTisma0JDRGluK21Hdkd2V2JiWlY5QWZRSGs="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
