---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/auth/login:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "401":
          content:
            ? ""
            : exampleSetFlag: false
