---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    put:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic SGdneTBBVWs4TjpFYVM0TjItUlh5MiFEMmk0QndWNDk2b0xKZmJZQ3NTNDM5TzdLbk1UOG5Qc2kxLTBPbXI0bDVHVTAycVUxUmNILW1MWXM1NlQwemdYa2NjbTRLbldMV2RqdWk0Ty1iRmZBR0o1eXZwZDBUWk8wJiRpQzJ6dEBjYjE3IWJnSDRFOGRrcXhpa0I0UmtxQ1FCNk1YTnZaTWlVQVA3YlJranA0aGlBNnE0Wk1RcTlLS21WRHZTVU9id2JKZnIyQDFFP3RHaWJvQzBsTHJoWlZhd2VzTXNQdmg1WVcxdzlLMyQ1V0VhdVE4MGhmN0I1RWZpK3o="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "400":
          content:
            application/json:
              exampleSetFlag: false
