---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic ak9ZaG1kVW4ubEpJZzptTW1sTUpKMiVVOFAzRzhQQVFjbzklZnRSSVQwQ1g3czBzWkxUM0FqJXFqZmpZYzBMbVFONHY3ODgxcyQ3N0d0UEFES29mJEl5SzJxWVVASm5DLVZVK2NAWHNEazRGdkt0bFRKSEVjdEBhQjRDd0dOZUJSQEEyJUVAZmRkZ2dFb0tJd1VCSnlXS3AkMVdrUFl1SkhrQ1RmVHkkTGI5LTNmSDRTMXc3cnJlaHNGaTFDR3VzNXdVZw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
