---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic UzZlOjNKQ05pMDF6MjNwTlh1U2RzV1dJUyRRSjkmTE1paEQ2RWs3TTVVTXVHTnpMOTRWQG9OeUBTLSVGQ1Z3K3RmODYmVjZHZmVIJEhYbTlYeWVaJE93UEVmMWY2MXY0T09AdGhmS1hiJSRHcXFXYmRGODJnbjNUUDRaM0xnOWkzcmtNZHF5dCF0SDRZQE1LaWhIcFFAeVJoQVowd0NMUiUwSzdIIXc2QzFCK3pBayZCd0JjZk93UloyeHNQY0gxcXJvajNCNE5r"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
