---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/1135/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bXdVQlhEOk53Myt2eCZlNkJodnEzdFFZSzBBQEQ1SVcxMUJFZz8/IVAmVDQrYj9MNCU0JVRu"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
