---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts/transfer:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dnhzU1p6T0tCejNZOmxyNlJYNmE3SjclaWdVM3V6amw2cVFRT2wrTHlHN0MwdHBoYTQ0eU1MUTRoV2ZsYWFAaGJxbGxiKzcxdjNwMjMwQHdIc0JAb3UxbHVVWi1KSXJmR2FIWnh0clRhVCZQS3ZPUkktYmZGZXErMms/LUZRJkclRzIhZ0BEY0ZLckBxVzllNk9KSUZLbW5idiF3NVdELWwlV3ZMcT9KZCV3ZTRNLXRWamd2IUxOVmpNVVUrVThickJKRzV6WmxPaTRvNUB3ZWt1UExJREpaJVhFcjAwQkwhVzg/cFAkIVhUS2xUSSUtU2VRP1RSOWhZc3hDZ08="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "400":
          content:
            application/json:
              exampleSetFlag: false
