---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic N1I3OmI5Z2lzY3NYOStAZiVMbE91Wkl3UitxdWhWWXE4R0FOOUtJZEl6JG1lYVpFVlYmZ0dhWFhEWWlOd0BsTGxiMGh1ITFxNm80NEEtWWdzeD9ndHQmbWNISjYlQ0V1MFZtZHV3a3B2TENhanFickd3WHZGNCFybzNqN1FuMjNIU1NicnFXbENhbU5jZ2FZQW5FVUd5ZnNrODVRZ2dPWUpQekZ0bGw5bXNPNWc0LWVWU3ZFMGVaQVlEbjNCVTFoV0BQLW9IdSFGUmdPb09XZ284eGpDblZteSQmJCVsYg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
