---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic cTlTOldjNFktUkMyUkZzZ3h2QkQ4R1RLLUVaSDQ2MkVEQyQ1amRIVVQ3Zlh1STdwOWd2MjR1eStCQTFzSm8rYTRILTVNaCstVWh5ZW5jZmw2VTlXcVV0V29jT2hsVVFmVDBKUkBkRHNFSmNwQjV2aTZoTislTm9nbStKVFkyK0xnR2lNJjhsdVExJkNKY3dLbVZsRUJWakRjNnhCc3p6MiFGQktlc2huRXUtIU5yendYMUVieEJZR2NOLVZqOWNOT1JwWUg5Ug=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
