---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic RktiQnlhb3hpZEZhWmNnOjNAS25VJCRmOEpPNGtWcGVMSFpjTDF1Pyt3SmJZamF1JGVJSW1HSGRxLTN4TytzdU5GQCFQaDIlUEY3N2MkcWx4MDRrYTZAaWltZm5pb3FyOEkxQ3F1UCFZV2dIMzZyYVotSVV6YWshbWRxQGdXbz82UFk5TmtVWG4lLUpJWDhESmkhJmRCbmpLa0J1YWMmLVBPYTM/Tjg4Z0gzTmYhc1RyTHdsMXViJVg1M0RJWnpRTCRkSXFnWVhWQ1B0LVNsQE5VbXE3aDUra2JLKzNYcHdOOTdWSWskP2s/Tw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
