---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic cnRUXzkud0xpVU9lUUY6JVhhayVNZmsrbUYxWUQzWXpwN25nNktkJDZvN04ldmxhTXNqQCF2NklASiZiNUBKMHJaZmdzaTJtJGNsSkRnY1d5SXpNbEpjSjZYOWpyZWwlQ1hoSEk2bGhQQFlkZTV2VGhvdWItNVU0ZDVFOEV2aUxnSVg2cHhSayVTS2pqRC1peVg/d0Q5UG1XMS1RR3FjUWttJTdJJm4zcDAlYUZBYkAtKyUtZXI5UDEyaGkrOVVSMy1YIWRzQGQ1bGJacC1zSjZjOW0tYkglSG56Jnlzaw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
