---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TjFwVkk0ODpYbTMhM0hMRmlWOWxtSGMzdXcwb2YlekZVN1VNQkJOaUZoZXRvRFlWaVFvZ042SEdCcXZFVHNOSCZmcDMtcE0zP0lQIVhzWm9Gc0pmJFdPbXk2MzU/bjRpJXNna042M3VD"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
