---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer-with-fraud-check:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic UHdOU3F1UmNvYzNlRUw6Vm04LVVvVzUzaXU0OFdya1BMNldIVElBeG5QeG5BWVpYU09KeGo/eXp1QDVHcWh2"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
