---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/854/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bFI3ekpuNXFRYWdEZnM6WTZqbFJHV0BlaG8hZEJEP24hZld2ek14JT9nNC0rUUNxMFpYTk5rbzBSMjhOMXdFcEBDdmR2Jk9lNVVuNjAlWHl1cGZiSXZmdUB3UGhaIVNSQkVsZy0mMjcrQk9WVDFPNTRYRUkyZ0BUNjUmUkkxeGVaSEpxbj9tSDA0bERxdys2Y3clZHRFJjZHcmJmc1Vh"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
