---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic V1NDck5JcGoxczohbiYkQ1BHcExHLVlJU2pMT1lnZndJUFVVZzNKIUpLRy1TP1l4Vmc0Q1lkSlk3V2VWP3hTMkpFSSFDRE5sSXhsckJONTFmJUJiOTNqSjhnb0hTSEp4aVMmIUMwWlgmOGJndCZEdSFqSCRCYTBXZC1wP3pGVmVqQFcya0htaDlSaHFmR1pJdEdvR0cxeXg0S2x0OW5UaSYkdzc5cGMlYkAyVDBHdXo5JTVhUzBpenlFTFJhT1ZoUW0yc2N5cElGK3V0Nzh2ZU5hTGdhSw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
