---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bUhlU3Zqb2d4OlB1MCZKWVUrYzkxRW1iZzQwYjZlOWdoOEdkQWwrblJ3JkZKQ2ltMTY1Y3dyY0NiM3ZGeVgzOXFkYnk2bWJEJWMmU0FRcWF2OGRkaQ=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
