---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts/747/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dlJyTHo2Y0tkNVJmTjNOOlpyUnFxRWRoazhQWDhQaXlwLXlhSDdqc3o5WnY0Umx4V1RZRkAtJE80MWRIYyQrNWExJFpLZTQyYjQwTVp3ek40JkgmaEUtbyFCTWZCbU1QYnl1YjMmcG5xMyVnODZkWlZCNTFXV1BScnVBaUcrZkc0MjFCUGZPOWxZOUhRTHpGQE5XK0F2ZHowTlMxQHpDbHZOTiZpRDBxMTJaMDFAY28yeUdIODY5R3AtZ1Y4RkJ0Tlk5bjZkTjB1cTE0cDZpTTZCZ3laT2UlY3Rqa0VlVDUyV3U3SEo="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
