---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TmZBYlFycWRsTDp3NVJSUS1SNU8yJFh1WUhPYjhxc1lmS1Z5ODJpZlJkc0orLXclVU9Fc1A/ZElkVyQhdUxzLUQ2VFlYIXRQZTJDTmdRN3FpZ3VURnpkOTZVQUU1S0NqbFMkQkZHYmZ0dXdBOFNFMWhMMyQ0dXc0WW8zSU5YQENAbHhuJFlkeGRIRzU4NGxOcyQrITdLJGxRaGktJktGSFJXREZKdm1EQSFWRXdKZnZkeTQyOE5qaSYlUytrS3ZLREp2aEpOUklDMWI0b3RVVHVtWmRpSUAlOGlaTWZkZVdKdHhGWlprTkdRZ2lieFJNRnFDeE0lY3dOaVZNQHh3JlI4RCs="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
