---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic MklVSFNqelA0OnpCc3lBIWJqd24kV0Y3ZHM/TU0tNHZLZ2lydnVRV3psUXhSNy16VzArVGVpdFRqVkhmYm9NRzRUUTQxSlpyZ0tadkNKSWZyQ0xpU3BAV3l1MDArREFwMGx2MyZ4MXQkJXJTZmN1ejh1SjczTjhqOFAtbmRwWmVFdFJhTWhQRjdKUyFFclN4YnVISHRDRnd0S2pTVkZxTU1uMyV0S1dAK2VxTkBLc3NCTmdKNTRFOThSM0xYa2VhaW4keVYtYmE1aEdMb2Vx"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
