---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Qk9yek01NmVCWWQ6YzkzMWFhd0ExRXRkNE1aayZNdXkyMmE3RFA0NEJMY2J3dEZHS3NESUNFT2RlbktNQSFOVjFyZGlQTjR1JXhLNVRQU1JRMzhReDdvZlR6S0RAciZLUyUwcWklZ0U5TkN5SmgzaURhTDRreDRVMiR5VW82S1lEVEw2ZDZScS04OEgySVhaUGRLUU9LN2shQjFESUY2WlExRDZZU0whZDFDbDlmQHZTckghbThUVg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
