---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts/726/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic a05XdjlCWTdtQzprQmN3MjZCMFlESGdKNWdxP3VRQTZKV1Qyd3ZDdTI/ekMkQVE1SE1RampsbE5Kdz8yclNNMiZCa3lmOW5SQkA3dW1obThzbjM2dWMhQ0lLck56ektoVHJ6NCFOczFrS1FOUEkyZHppUFFRQVp4SyZtYmN0WWUybDRFeVJvS3hTSUAycXdvOGdleHV2"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
