---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/deposit:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic am1wWnI0cjI6T28zIVQ3TC15IUBOJkJndFBSc2JkZXdQdFBZeEp1YkJOYmxHTC1BLVdmNGNLZ042dDBUciFlUXkzVjlnNnRrbSY5bWpuTXNmWmh6WGckSmJWNVglNGpKTmpATG5uRXZDajREckBzZnZ2b3ROU0RyZkRBMWlVT1k="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "403":
          content:
            application/json:
              exampleSetFlag: false
