---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts/731/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic ZElrdlVQSS5MY08uOkcrRXMmaC1qcUhGWk0mTzl2R1hWITFWIVRpWVE0dz8lSEF5UWdsa05mSFVHYkg/aWFRTk5CQ0dYM2lyeG1WK3Q1IUpNMlBaOGh4dTVtYkxwLU5BbVVhdTdud3M4UHRra1o0JVFiYmJVZERYcFNEdG1OZmEhdDRYUUxwT0MkVXRmMHpaVTUydTB4"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
