---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dlZwY0d6WnM6Q1NPdDB4Q0NoWSVaNyYxVUNtaUVXWCstQDBHeUBxNSE3cCZUNmFzYVBnQVNHaE1Oc2YzWjhtb1RSQWVsJXUmNjlRMmV4bENTbklJQzlkeWh2LTB5djlIUFI2SU8yVTNVNGFRYWFJTUNnUVElVVZ5UiVTQ0skMWN2c0FzWXBZOGF4V3Q2dSVaNGp4MkklVjA0a3dlK25Q"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
