---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dE80OkdLeXRnc1dQaS1RaWtTITR0cEx1a21SOEhQeDlTVVh2QnZzR3pyJVV5Wmg0ZGFwOUNZbmYrQE01MHBXV2tTQm9yNkwtZ1VZdzU3cGlGWm83cERKM2tPWEdseGhJa0ZrQ3hQUlVxTlJmVHlCNWNhWXFraiY0c2tSeVhFRXFXRGszVCVTLTdGbjhQYlNTUU5HQz85WXdkV1RpMVdmQ0hiQ0QzJDY4bXkwRXc0WndSQnlwM0BHRTlqJFRVYlVJZTBsITBiQE5Na3pROS0lYXphcU9aNUFiVCt2aS1zUXc4ZVp0JSQrN0ZqRGVLSGRQ"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
