---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer-with-fraud-check:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic U2wwQTNORDM6bSRNaVY/RVR4RVV1S2llb25aR2hLdmRyWUJhMCtIQmZMYjZMUDBSRk1VRCQrZ1IwP0FiZzZyQGhIejFJNndieUhMK0JGRjVCNjNJaEQtTlpAZFpDazJQaVFsVnQwdHBaejg5JnBrK09HTmYtNWlwaTAwM0IxVGRSNVA4VkBEdU9ZM3NFTHgxUCFSUg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
