---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic NVNzTmI3RzdEOkplNCZEN3I1V0tHN2MzNnc5WUkzeGhJejZGc0VqQCstRG4tNVdOZCtBS3FJd3EkR3NPeUVWaCZOejdUeW55JDRLeHYxbVY4VysyMXNYLStsZ0R6SFh6NzZsSDIyT0E1"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
