---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/admin/users:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Q21DNXFhT2R3RHJWbGY6TVVZaTN0WDR3USFza0p2WE4hVEVRMkQ2cFJ2NWlWVkF5OUYhRmV4OStYRlhnSFk/U0B1YzMmUVhFQ24xOVppVz8mOTQhOGpzTkJyNEA0LUtWQjVAM1hYWUdHbTBpP0pPakVZNXRCYW5hUVlkb0w5aSFrJGozZDlhLSFVNi1Ya2VaQVV2dTND"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "403":
          content:
            application/json:
              exampleSetFlag: false
