---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TnptcHA6Jmpkb2wxSmRlJm9STUotVWlTcFRPSGZaTFo2LTJDbGJ5bUltJkB2RUVVbWJwZ0BWWDBFZWpsZnNWZHJDWTRwNmI0aWltc3FSIW9hN0t2ZGxIQnBralAhcE1qdD9jYndtLWtETVZzJUMrVXBjbjlaOGpsb0RJY0gkSSV0U2lzbUdHQjlYTXlQKzMlaTNxcEZNSFJOQExvVzNzVFMwa1lPQXlGRlVLP1RvellqQEhuJUhHWFo5ZCVHdGMyMEAtcFI="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
