---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic WXlxNTQ6RTh1RnBKVFpIK0lpN0loM3Z0Y3VoP2tyaUZtWHktWWM1S003WjE3akdaT0hjanlvIUBAQDVESWFzMUlFJnluT21aVnM0ZmpzLW0hMXBYNVFnJTJsa1QhQ0s1dkxEelBiOHFRR0syakRXb00/VmxIYktrJlFRUUh6NmgtZEN6QGZVNldhd3N0JmZHWUxIbkZWQHQ="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
