---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic c1owcTc5X3hrM1c2aDpPcDYkdGRAeXlnSGt5QW1JaTIxWjVxKyU0b1BNdm5ycElMY2pwSzEmNWoyaW5RRFBpcCZHU2tzcXckU3V3JGordDZvM0FlaTdaZHZVYytCYiZKbTR4SWRVak94cnJyIVZ2ejBSOVhhSmNKQVE4QGdoZDI="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
