---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic OU1lMHc1ajotIWtFSFZtbXQ5JkRwVUxwMSYxcGpHIUwxYzFsSWI2QW1XZDBMSHlxUTVFVk41OUhVV1hELWVQd0VkbDM1ISVqPzVxYSFiSVY2UzRrbWw2NUxSb1lPUkVHS3dWNndZYlN1KyRqbHArJE5GIVBrREprVnJZQERkNUdJcThnQFF4RkdxVVBUbTh5IUd1Zk9ta1pJMVlzYmlOSFomd01DUFBWekxzTSRRUk5kITE5MnJrUFcmJGlsckR4M1ByUiQ3UmpzMG9tcm5hMm12SEBmaUZjb2FhTzVvR0ImWUtONDhDbkptY25Rbzl4VWk4YXRJNE9SK0g="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
