---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic d2FrRGZheXJyOjR4JER4Y2RVZkp5Rm5GWXExYnN2TlYmJnM/dU5JcUJXajRNS2xEWTZwISt0eiE2K29Id2lDRUowRUZULWZVcjk4bHlkcCF4Nyt3cTBMR0hMRFQwYXpOREZ1ZDhreGExbSZxSjZlK29TM3NxeStvJU1YekBvdkRGMGZsJkFZRnc/TlltNzMyeElyTnMyY2lmQWFDcFFSSDgrQGs4akgrNCFpVzdvLVdOMmxPbU9CLWQ4aEMwVFQ/QmduN2whTWRKS2dQTk4rK2NhUnpQSCtsbXgwQTJWRGtsdkV5TTlHbVJwY2tpK2JNeiZN"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
