---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic QlY5YlRhQVo6QiFDdVlTWkUzJWJudEZDP0A1enctdmgtN0RxTW00LU5lMWpAMm1LalcxdHh6PzVhZFFmQXdQUiE1U0FSVVc3RDhCTksmJUNIelBsZ3UzQXg3RXc2cWJDSyZYa2JtLWJDR0IhZlZ0OE5oZE9jZm9CV2g3c0Uka3EwNjBrR1dIWE14TDVGTjdHVFRSIWFxaTNIZ2pscm1FP1ZVejJqMkAyeTglbDVZUw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
