---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic VElBanA6JG1McFZ5Q0I0eTdpSy1EOSF6emtJaTJGU3RaSjAyU0MwdzhGN05ZdSFENkE3U0VZeWYmY0N0S2VEZTNYek1EV2xkTSYxaCVMRisxdk5TUW1xYkR3Uy1ORjlUR2Rqc3crb2hNIVVkJGg5b1MxSCFleWpJTyswbkwha3RCZ2tJOUZFN3chOHFzY2lOeWU1YmEhY0hEMkRTZUQleFFKOHFHMFNzRHkxaGREd1BOdUk2VjJDWTRYT0E5"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
