---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer-with-fraud-check:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic WnFPLmRGQldjNkIzclJtOkFsNiVSWVRjJTZKJmtnb0llQ1Qka0V4ME9JZyRsMnhKajROSXkxMFFWM2o0dmFKQ2RxVmhhZUhuIT9AZ08xRTlreSRiU0RALW9MRlN3WVVURmxNUlY0"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
