---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/838/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic eVZ6ODoxeHJjajM3SEJpR0JhNkdFZD94RVR3RDFGV0wrd25ZTWFOJTNhIStoLSV6RzZJMT9BTjl5YUpxenZiS2FTUUJ5dmdCMy1KK0hNNXdkaU1jQGJCJkZVNUR2ekx5YjlocXpSdm8/ejFrSW02bExyMElxJkk/Y3FucmdHLWVZbG4xcWZSS0VVcnBVaWQ1bzNPekFBJWZUcmItUytJbg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
