---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic X1luVXB0dU96OkxyNiFLeE9UZk1HSkVYdjZIVSQ5Y0h3KzNadiRVIWZjb0NLZHRLekYraXo1SUpMPzBlM1YkRWNDS1lD"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
