---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic cjEuRVJYOm4zMmZDJXNnM2I/YytaSzZMNlRAcXc4NG1tUU4yOCQ2NFBNbjRIMkU2NkNEQ0pxYStPcTA4MlhnQkpRWWIwcG04RzktRDhwaTlDUE5TOTNBWW4wMD9YdGJoTm84LWNZNis1RXZpazczMURDNkV3VEl3RUdxMzVEWT8zY1hYblArLWQkRkhtOEJyVVUlczFIcnEmZEg1V0ZtTm1MUHo4b1o1K0VIS2E5R1R6eVZTRThAWHZvUEhFIWUwcjN6cmdDNmg4aFNoenp1RkRJd0NJWCRodDdseHZnPyVpUEo2OVV4JkhjSkhAekp5QGVmM3RLV3RXYS16ZjhjMzVjOU8="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
