---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic VnRQSTdBdC1HLjI6cVFHQHhDY2YyWGE/Jk5ZYXo2OU5EUTB2JFZ5dUZUWkBiQU5VIU9VNjVYTE9jQSFrS2V0ck1kUnU/K1hzOHNBSGZ0TEExTmdFRj9YdGg5NUc5ckB5JGItNmx2WGUmdkVSbnUmR1ZVY0FNVDM1QnJaNXN5WnY0V3lUc3dzOGo2dVEkZlRQJXczMjEtakZzQlhoN3RUakVJRT9FRlIkZmZqSUxPSExaV2prREdqV3lIeUNtYjFBZ1BDSUJQQ09hYUF2Y0hiK1FySWc5UElFcnNBRUYweEZDY1ZYMA=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
