---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bmZUMXA2SS5EWG1CcjpIcjIrQ3ZQdjd3dlNtY3dhZXZnQEg0QmcyWHk0WHR6RExUelE0Y0pLNUZHR2ozNEVAWD96OA=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
