---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic SVI3N0FiMzpoUEQ0VzRHVDhDJCVaM24md0pEMmRwRGt1YnZMVXRUYkRZaURPTVV1Z1R1V0FXT1FXTklFY0NiJDFxIURXdFJlRWQwRnUkbFcteDNJTWJGViRrTUY1QzBXYlJkJj9GZHhlREFoVDNnS2hJZnoyWmcxVXFLRGxuJTJpQWtVNUNBZzkxJlhSLTNXb0J0OVFqVnlqc1NhUCEyaEhUSnNVQCQ4Wg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
