---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic ZmpqQmcyTG86RWE4JjNrVzchVFhOaWpodSZJQzBXNkpHY3FVbnB6cEtpP1lQLTVWRCYmclFETzFAIW85dSstQHBTITJ3djVmNXJIckRjaDkyRw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
