---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TVlGOkZvWmJNRiR4aUNwT3BFRUQxSDg0UnJPb0Y5cnRXQzE/SSYzN2VvdWRlLWlJbVNWNnJ6QXpicEA0OSRkYmtXJGxBP2EyMUxyOXpockk2dTA3TCZtJUVrRURzRUNZJHUhajhTNmhPcGs5P0VEK0dQV0JjY3F0YzRnWUZ4PzAmaGhkSk5uQTM4MGtncWFz"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
