---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TXRuVDNBUzJkcXlzMXE6VWM5LVU0YnRtWkNtcyFqUEhEYWpEUjdyOFZARmZ5akdZUWdUc1JEJG5YUDFwYU52UHFvZ3h0bjVVOA=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
