---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic YW51U2FXQjozZEswYTZ3bUd5K3FDME1NQHAzQFAwWXU5Uk1NYVdxZjlnUCFlVTchMiVJSGRwVDJuTiR0RGZTOUp2V2trRDZsQ0x6TmdsSjhvU0UmP0xLNXhuN245ZDQwQHhEdW5DZWRSRyVacWlqQmZuYWVXRDdCSkVObEl6QmJsLTBFRnh3Jk81NlBBJXlkWWVPblJRTkVWKzloY2NN"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
