---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic ZjNaNEZLaW9iLWo3OiUtU0xGTnIkQkR5dnpsVUBFbFZiNEwtQytabCFSUForQHFhdGNOWlpRREtWRTNDWUtIbDgmd3RNNkZkTzBuK0RYeElFeXIyTDRxZERNU0MrZEt3aVZ4MTRyMU1QVCVGckkzczdrNGJ5d1lUcktxSEpXQEBAeiFEQmFnYnBFJG5jNzI/TWpydSVWIThhOGEmR0VqMVFFTCQ5T2lRJWdkN0gyaDdQV2puYXYwJg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
