---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic M0U2d0wtcFJZdzpEWk8zLUZjVEBnJXBTUGRVcGdDT0xNV1g4dC1aNjZlckFqczhlRmlrcmZ2R1h1SUNAOXV1dUdXK3J6RjkxKzF0UTlxaGpAd3NTNjVLU3ZVZjFuV2Q5SnJRQnpQYjVicSE1UWd1OVlrMSs5Y0xQUks4Z0BmM2pLY0BQIUpsNmVkbXNsOSRZUFhoT0VBdWlGQGlqeXZ5azhJK1pET3FmUVdOZD9OZVAkTURYWmcySExFNVB0"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
