---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    put:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Q1EtNnpob28zaDMuOmhFcHFYSWUyQ0V0WktGRFdUVi1RQ05ib0EzKytLRUhyTDNMRSZVVmN3Nk91QCs1V1ZiNU8lTWI4NHRmNmpRIVQ0T2sxcXBRVTFKJmJSamZEeWlUa3BiTUxNaFdsTzRSM0cyaTIwQktSTDNqZlVmZSYwTGl5TjF0NzZFb09UJjZVNUpEd1R6MHhDJmZGOUNkZVlXSGxHRXJWRDEm"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "400":
          content:
            application/json:
              exampleSetFlag: false
