---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic d09Kei5xXzlDOkIwK1gxODVPcyZoR2MyQXIkeVJuU0gwandaNkUzLXhAMUpBMUJlMXZidkBPdGFuJW90Nj9Sd0k1VXJ0V256P1libFQzSnI1WHNwVTZ4JGZEZz9lVmowLTE3ZkRYT1RhblF6UDdqdy01OVIrTE9rY3NUeEBydFg5TXElaHNpRTVjWFclQXJLTkxtbFIwOU04aER4dXh3SFhqRHRjT0duZnZBdU5wVUBxMWZRaHpndVNHOC1UaTV6YjNEYmsrdSFpWEQ4SDhDRU9AVnVFdmVNJllBR24wUXFwVXFxLU5ycGl5WA=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
