---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic R1JxWHk0OldFN0RkdmdqTWpSeEI1YkdEb0gtSkRJZnVDUytmeGFPRzllQmIwblNCeFJ2d3QhVUg0V1hPV0pqRmplUTM1S2xFMEdtdmU0dDNhSzI1a3VHSkpnMXNGJGFXMkJ6SSVnQ1BMMFRmWSZMcGdTaVdlcGtASXhDJm9qVzIyJEhnZjZIdEdEQGNpaUJoQlVRUks0VTJPZzUkVjQtWkFzUD9pem90UzRyMmZAUTZRTDFmSkohOG5qc0hrTkQrMm1WVTJsITBsUWRoRWhxRmp2JklGbHUlMU1yQ3FDdGM="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
