---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/1140/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Nk5YQ1NaWHVZZ19YQ2JyOkVpMSRwb2JRIVlSanpjSyVIdVBmOUxGN21meWR5c0tPekBlQXRQS1ZqKzBvTVZOYTFjTWk4bDVYdnFlQThPWVFLb05DYW5wbU1ZJkRrc3R4"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
