---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/992/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dFROUmlRMnA6SmMwNytJYStzQyshVkZzekJkViYlRkFuNGNtb1V0eEJhcWF2SiY2MD84RmFZLTBCTWxLeUExRHZXTmliaWFzYm1KY2lhM2lYejh4RkhzS2lTczhsJXFIbGMkQFlXOExjMWFCbyE4MXo2K2kzOWs/YzFCcyshIWdGJjk2QEFiTW0kcEFtY3k4djBSaVhHMnBOcW1CNC1BdzA/UXNVNTdGRmVUa0BWT0tZQistWit0Mjg3ZW9ibHF6ZyV4REFObFkxa2wyVWdMM3VmOURpTm1rNWJ3JFNRWGgyUmdZbkUxUEJHTlVlYVhETSs="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
