---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic elM3cGgtZ3NiOndKQEtKN0xXSmclP0h0LVgkSCRiRTFAJHI0VHBCZGozeC1QIUhNcVhCMnlzdTF0TDgxJSRBMUxQVTVZeHFsUk44dzFPZERGdW1yLVgwJDAzUjFhbmJKZT9xQDQkbGtUU2NzJEI4ejRETUZCUm5jbmdwMmUxZmEmRT8tRHNRaXVxJFZELUpGWTJvMEZWeXUrYzhKUEJ2bW4mQHpz"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
