---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic OFFqWi1nRDhFOlFzTm1qTXluWUlKMURoYTBjbVpVMU8zOURiQDhXV2pyc0BjeCVHUE9pcHpYdm9ZJE92Vm92M3ZSazdJYjhwYzlDOW5jM2ktd1BSJHBmZ09ZUFJLJWNAZVVqYjQ5SSE5N0tEZjBBNnAlSzVxek15JTVzQiZDPzNLbjJIWFdhIWlnTVR4S3NIVW45cFJQTU14WXEzUkFlZkoxcDVWR3E2JkszclZRbkZXNlBALTg3MEBAMm1sYnNGJHptekJvOU5tckM4YW5ENGQxUzFpQ2VpRTFZUDc5VXo5dyRIeEoxZUNTIXJhQmU4YWsldlhENkVnc1UlS05CIWZOcVk="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
