---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic eDkuQmdWbHBqOjFtc1dOODRtWEFmKzZyOWt3b1ZKei0rRTRDUFowTzB6MlRUQTR5SlJrRVpOQktwQVI5WW16d0JqJXZAUS0kTnhTSWYkcFVsS282NnkwOENyS0ZvQzNWbEJ4d2NhaSZJTjg/TDNjYU9oc3QrVUVJZm5SWTBMQHVKNTBFeWVKYyFVP2RTSFYxcVA0QXg1TUJiSHlEP3RAaHMmZ3c="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
