---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic QkFvM0hnOE5hdzFnUjhYOkJ4dCQ/WFJleTRXUkBSa2dJPyRTNHFrSzVWNlB4aFE2MmtXcVZ5OWRQMjl2Jm55bjVNbUA2K000RDJkWkZRUjFYQll0eiRlbzFyazd3aW9NVWVaMDg1Q1htLTVZbDdvYWZtMjd5UUpJK2Z1Nz8tZklAbk5RbWJuQ0BHUlM/WkNrZkRlTENLKyU="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
