---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /accounts/734/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dms5djBJUjpjN3FYZmtuWUBxVnRKK2t1TmIkWE05NCV2UFNkcmx4QUEkRCtLY2I3eGZ5SnRNLTNwaURPNHFUcldlJEFqczQmJVVFNFp1QVZEaGU/SFBaZlpYRC1yZHdyQGFHWmN0aG40WG1KNXBqd0ZvJVVrdyVKVnFXTHNUUTQwMXVKNG5xOGxUeHhjLUlEcFF6NmhFIUxaRy1NR05PJHVrWlRsTXdzRmlqbGVlT0NhZDUtKyVUT0dqWkR6K3JCdVhWckRBMnQ1MFYzNWdJ"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
