---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic enlYT19VYVdjTFFUazZ2OkxjOC1ON28kQzNjdnNhLWxLWnN4Z280eE9sZ2pjTGVQK3RoIVlFOD9oMXB6MGVGYXhSM1BENG5hZ3l0SHR0N0tPMjE3VUMyM3BMbGpBVE5aYnYkdU1DWG1xJlZZdDA="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
