---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic RjZtMFM6K2JzbE5RWWYhOUhHITVwRXJPMHhRSzAlRGMzU3hEZTNRQSY1aTcrOXZ0RyQ/JiVuT0NZR0JXeT95MFdMcjglNC1Cb210Z3ROYy0xemRvQzZQbkdZaW0lNjEmJTZrLVhxTiQheWNzZlZvSzdPcFQxS1RAallXYkxZbnZtYWxJa1RMbDdAJD9ERjJ2M1ImVnM3NWlLT1RySVZFRWc="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
