---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/868/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic VHJmY0lFM2ZwVTokbkdVeVFDWmVlaUhzTnRJVXFxZnBvNHNMdjJKMVBtcUIyZ2IkRVFtZCRBRmZYS1VheFElY1FWR0lvREg/ZCZUN1ZZSUVNR1E2UnVVUnhjMTNxbUZkNy1DUFUtUmVuaE9MMVl6LXV6NHR3SFl5d3RhcEgxWGVqejhmbGNLTDRrZ2hOSHhBdVBOSjdSMXlqOTRiZUBpWkokaiZMIU96empWTVNT"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
