---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/deposit:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic cklYZWE4UzM6ZTErZHElbiU4emVaUiF6T0hSZG9SLVczaHVJYUF1PyZVVGRYQCU3NmpUdjlnbHdJQzUyQiFSYURtcTgrJFUhR1VSOTYrekdGa2E1TEBHNCRLcXlFJXkwU0w4UWhOPzg5NUBaTTRudXNNJiRMNU54NVM3QFpvSTY5bk1Yb29MWUhZcyFpdyFpMUEmaFclbU1KSTlBQlNyZUlGUTBRUWZDQg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
