---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    put:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic NjNWbE86c1pROW12WGFycXZ2M2NrLVM1aXdHcUZwMWFxP2FPdSQxT0J0UXZGMEUlcUNQUkNkJVRFeG0zVktickp3b2FsdldRZk5yZ3NacG9KNnozbVZ4bmg2WkluMEJaIU8taSRGYmE/ZFVicDBwa0VWSFZGLWs2ZElySjh6SzUmcUYzMWxVWkJHemR1Z2hLWXVuSUNPNmZZQElCTGR2P1lHUlBvRGtIdkdkNkRVIUp6"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "400":
          content:
            application/json:
              exampleSetFlag: false
