---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer-with-fraud-check:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic cUczOm9ZdG5DYkskYkhGN3A1YjA5V3RucmNoeU5ma3ZueW8kU2VrRG1hRkJAYjFnK1VwZHhiVkNYdE01VCF0OSU2cGljSDBIVmxtckZQdUJCPzJiMmVDREN1NlpIVGhJSVRuVkJDSW0lJFImUCRUMkVUQ21uTHJQYkNAanhNUFMhbS1NNXowQUklQU04NjU5Y21E"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
