---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic RkpiRi11bnVrT2tlTnJyOnZUQWNMZnkxUUNHbXBJWXpXQlRpUDFoVFFwdFdqejZ0SHRUWW1VekQhSmcxRlVxJVdiSGo/SWQmY2FhZCF2d1JCUHJNTUtDWGNrJjArWFdTeGlhenhIdkJmUFJLR2JId0AkTDYkUjFPdyFSbWRnczBUbzBwc3VHcTl2ZDIyaFZ3UjdKNTVvakBVcGFHanJ1SzdkIWdDa1pNdCUyZDlnOEVzZkVtanA3Rm4ydiVOK29xWi1aT3dKb3ViZjUzY3dVdUtLK2ZqVkJF"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
