---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic R05EVHo2dUQ6ODhtODU2JTVwZEljUTBKR2h1NGM0JXY4LXM4UCQxaXJSUVFBU2Q3SVM0ckZYVVVUV2p4TVJFIXMzOStiSjF4S00wRnhJaHlKQTY1WFhhc1NDRFY5eWVBJUBRSzlWY3UkWjY0djFPaWk1IUxxWXZTTG00UFNPVlllbW4lNTNIRTVLUGlFUGZsbEtUR2hoQ0VpSnl1SG9sN0NhVTU1dXQya3JRP0xWZmt0M3p6R0J4cmtUag=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "201":
          content:
            application/json:
              exampleSetFlag: false
