---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/816/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic bGRpb25rOTpHbUZVazktenJyLWJZZDlDVkdUeTlHbVNFUzVSdUshWHhzS1ElTTlnZzZHUXV1MjJBTEhzVEQzSyswUVZVc3ZkJjhjVVlBODNAWE8yWllQcWxNS0orMWEzZD82Z2dRcVpiVnY0UFNzdUNFQ0NvIVFjSU1oR2VmeUZxNiVuMUVOJDNpNlpBcGdIYXEtZFVOMnhhenZNOD9EakJFZnorYzBZUjkxJE1aejNpRD8lMWx5TjNTeU9zP0NzViZqUVFWeURSaWtyTUZnTDJQMCVteW4mOGlJRnRxR1NyN05QZ0c5Jjhsb0prM0JweU8hZ29qQnRk"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
