---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Znk4OmdRS3Z5THghK0V5Nlkkc0BFS0pWWmpuV0ZDcXVSRHN5YT9jJnpKSjByIVhjZnVtWCtAOEREbTVVQGlCYVlEZi1yYWY0WiVUJDh3VlRRZjVkJjUlMndRLXEhU2JIZUd5RW5vZ0BNT3JHMURyN00zVWlJJUtoPzJnMlE0a0dzNEBGLSV6OWI5UTNaeGM5ck03VWJ0YzNJNUJ4YlZjRlBDQzJOOU9hYVFzOCRXTGtSYUhCMU9OM1E5MD9tIVllY2t6QA=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
