---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic S1laNmJVMDptQ0FpP3ZqaWZ2LTZ3a1hvenFwc1YhRTlmWjJNWG1BdEokc1ZyMm4lRnlMc2ZBQll4VFRqa1ZPU04zd29zV1RaYWxQNzgxY2hIbDh2JGs0YWZ6R2wzMWZDa3ltRXdoOT9PbiUxVm4kN1UmbHJZNVdqNlFRZDFWRkVhLXprQyFhJnl5VVRwSnd3ZUM/MjgyeWNKU3ZWM3NhakAxUXdzQCFMZTk/NVU1Qll6P3VzTnkkbnE4anFhekUmSGNOdWc5azQm"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "400":
          content:
            application/json:
              exampleSetFlag: false
