---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic Z3h6dEVZVkg6JUs/QzZsU3lMc3JSWnBzRjZESiRVMyRCR1QtYjZpJFNvcHE4dzJnSkI5ZiFvaHA2MlZlRjd0dmY2STk1K2RyOCtzOFd5ZWZPP0ROUzNlRk8kR3NtRE9GcnhnaC1QajIyRisxTnljRUV5eFFuSUVUMTglNFhPa3BEYzBaV0VtUHMhdVhJcmZBYnM1U3lFNTBFRW10UExDRDMteg=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
