---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/1119/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic dWR6V0dtOlZ3NS1MS3dIWFFHWWV0c2RBay1ucDNHWVZOUzF6NSFjQSVqZ0hDYzIzcGRSVzR4dGktWkQ5eVhpRzdzZXFKQzNYa1NZJk14Y0hHKyskISsyQjAkb3ltTzcxM3FNSjMrdHZvOU1ASTB3a1RkTDdUSlE4QkVxK0VQZzRqUVdrZ3hv"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
