---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/1079/transactions:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic VnhfQkM3Ujp5WE5uP0QwZVBiJmw3eG8xP3RvU0dIbDVwa2hDTDYmSDh1Vjh0UHdLcnJEOUZwZEpKaE1IYnlnVUs3azA0QVVOWDVtODZFWUVzM3J6c1BYWVppOWNFUXJ0QUpxNnhtU3pkPzRER3NwbUxhV3VlbTA5ZDNNRUtQSy0zUHdEdVElQUlNN1U3IXNVNXphaE1BOWJKMTNnU2VFP3J5eUx6MzVyUlVMdE1PbWZsOXNAMw=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
