---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/accounts/transfer:
    post:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic YWdfUzpWUkRlNXp1T3N6OUczTXVRSmlDcndObjBIUFlWeUE5emJUeDRyJWc2JVoxQXpoR1B4YWpGWSRUa1JvTFNsdEMwVlYkbko3ekcwK1BXUEFjME9UeT9zSUdxNyU4WWs0OStwNk5ib1Ixd3B2WVImcXlMaVFiJTNQN09aMiRHUD9WeWNlZS1AYjdqRGwkYk4wSDJXWjlJeUhjalA3JnlLMXZiUHdOdTMrQUBURDR5bXVubk1keUFaNHp5MWEtaWY4aEpZT2drbWlnU3lzUTlQbzMtbGR6aThHN3ZQU0wyIXlXJkRaQ1gwWUFGYlBCaDhPQVZnc21MTjlCc3pLMQ=="
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      requestBody:
        content:
          application/json:
            schema:
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "403":
          content:
            application/json:
              exampleSetFlag: false
