---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/profile:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic UGo3aUc6YklAUkk4JjJMWXZAJGExVFVSM29DZUFCR1Y5PzRlN1JWbzlSNXVnZzZyN1BtSVVTaXg0cVBIaUBkN3BjYmVnVHA2T3BkTy0xVE44S0pramYyN2tCZVlnM1JVTyFTVDFEc2M4dTEkdHRIQFpKcWtFZmU/TTVVSXVIRCZRVGhjYnQzN1QxU2tOeWdMd0NXbG5pP2chNzllTTNGUHZjakVwNjJzdlZIWFQrWHZjOG9ibnlDMTd4cTBIVyVlTlpZN3lwYmxzbzNHekgrJnVCckZOZSYyNEF0byskaGVidlFP"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
