---
openapi: "3.0.1"
servers:
- url: "localhost"
paths:
  /api/v1/customer/accounts:
    get:
      parameters:
      - name: "Accept"
        in: "header"
        example: "application/json, application/javascript, text/javascript, text/json"
      - name: "Authorization"
        in: "header"
        example: "Basic TTF4NEw6JEYzQVhFYVR3Si01VGFYOGMyd0AkMXYtN1pjLXFGdXpqcGNkMEB2ZnRiekpQNDU2MSZFSXZTVHlVQHlmTFBYeGthNW4/IUs5S0ZZLTNyUGFxTjJNQDIkJj9od2VDSTlqYlZzOXpVRUhjQTJCNkpDIThOeGVYNjVKcWRCVHhtdmdAWFlkQDQ3dHJmMWFrdVJoWHdlZ3RHP0pFb3JSNmFRSnVKaVJFK0xL"
      - name: "Content-Type"
        in: "header"
        example: "application/json"
      responses:
        "200":
          content:
            application/json:
              exampleSetFlag: false
