name: Run tests

#trigger
on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up review apps and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven

      - name: Set up Services
        run: bash infra/docker_compose/restart_docker.sh

      - name: Wait for backend startup
        run: bash infra/docker_compose/wait-for-backend.sh

      - name: Run tests
        run: ./mvnw clean test -q

      - name: Print Docker logs on failure
        if: failure()
        run: docker compose -f infra/docker_compose/docker-compose.yml logs

      - name: Run Swagger coverege report generation
        if: always()
        run: .swagger-coverage-commandline-1.5.0\bin\swagger-coverage-commandline -s http://backend:4111/v3/api-docs -i swagger-coverage-output

      - name: Load allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build allure report
        uses: simple-elf/allure-report-action@v1.7
